/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 41
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 29
#define ALIAS_COUNT 0
#define TOKEN_COUNT 14
#define EXTERNAL_TOKEN_COUNT 0
#define FIELD_COUNT 6
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 5
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  anon_sym_let = 2,
  anon_sym_EQ = 3,
  anon_sym_eval = 4,
  anon_sym_COLON = 5,
  anon_sym_conf = 6,
  sym_step_operator = 7,
  anon_sym_BSLASH = 8,
  anon_sym_DASH_GT = 9,
  anon_sym_LPAREN = 10,
  anon_sym_RPAREN = 11,
  sym_line_comment = 12,
  sym_block_comment = 13,
  sym_source_file = 14,
  sym__statement = 15,
  sym_let_binding = 16,
  sym_eval_block = 17,
  sym_conf_block = 18,
  sym_reduction_step = 19,
  sym__term = 20,
  sym_lambda = 21,
  sym_application = 22,
  sym__atom = 23,
  sym_variable = 24,
  sym_paren_term = 25,
  aux_sym_source_file_repeat1 = 26,
  aux_sym_eval_block_repeat1 = 27,
  aux_sym_lambda_repeat1 = 28,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [anon_sym_let] = "let",
  [anon_sym_EQ] = "=",
  [anon_sym_eval] = "eval",
  [anon_sym_COLON] = ":",
  [anon_sym_conf] = "conf",
  [sym_step_operator] = "step_operator",
  [anon_sym_BSLASH] = "\\",
  [anon_sym_DASH_GT] = "->",
  [anon_sym_LPAREN] = "(",
  [anon_sym_RPAREN] = ")",
  [sym_line_comment] = "line_comment",
  [sym_block_comment] = "block_comment",
  [sym_source_file] = "source_file",
  [sym__statement] = "_statement",
  [sym_let_binding] = "let_binding",
  [sym_eval_block] = "eval_block",
  [sym_conf_block] = "conf_block",
  [sym_reduction_step] = "reduction_step",
  [sym__term] = "_term",
  [sym_lambda] = "lambda",
  [sym_application] = "application",
  [sym__atom] = "_atom",
  [sym_variable] = "variable",
  [sym_paren_term] = "paren_term",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_eval_block_repeat1] = "eval_block_repeat1",
  [aux_sym_lambda_repeat1] = "lambda_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [anon_sym_let] = anon_sym_let,
  [anon_sym_EQ] = anon_sym_EQ,
  [anon_sym_eval] = anon_sym_eval,
  [anon_sym_COLON] = anon_sym_COLON,
  [anon_sym_conf] = anon_sym_conf,
  [sym_step_operator] = sym_step_operator,
  [anon_sym_BSLASH] = anon_sym_BSLASH,
  [anon_sym_DASH_GT] = anon_sym_DASH_GT,
  [anon_sym_LPAREN] = anon_sym_LPAREN,
  [anon_sym_RPAREN] = anon_sym_RPAREN,
  [sym_line_comment] = sym_line_comment,
  [sym_block_comment] = sym_block_comment,
  [sym_source_file] = sym_source_file,
  [sym__statement] = sym__statement,
  [sym_let_binding] = sym_let_binding,
  [sym_eval_block] = sym_eval_block,
  [sym_conf_block] = sym_conf_block,
  [sym_reduction_step] = sym_reduction_step,
  [sym__term] = sym__term,
  [sym_lambda] = sym_lambda,
  [sym_application] = sym_application,
  [sym__atom] = sym__atom,
  [sym_variable] = sym_variable,
  [sym_paren_term] = sym_paren_term,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_eval_block_repeat1] = aux_sym_eval_block_repeat1,
  [aux_sym_lambda_repeat1] = aux_sym_lambda_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_let] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_eval] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_conf] = {
    .visible = true,
    .named = false,
  },
  [sym_step_operator] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_BSLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_DASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LPAREN] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RPAREN] = {
    .visible = true,
    .named = false,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_let_binding] = {
    .visible = true,
    .named = true,
  },
  [sym_eval_block] = {
    .visible = true,
    .named = true,
  },
  [sym_conf_block] = {
    .visible = true,
    .named = true,
  },
  [sym_reduction_step] = {
    .visible = true,
    .named = true,
  },
  [sym__term] = {
    .visible = false,
    .named = true,
  },
  [sym_lambda] = {
    .visible = true,
    .named = true,
  },
  [sym_application] = {
    .visible = true,
    .named = true,
  },
  [sym__atom] = {
    .visible = false,
    .named = true,
  },
  [sym_variable] = {
    .visible = true,
    .named = true,
  },
  [sym_paren_term] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_eval_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_lambda_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_body = 1,
  field_initial = 2,
  field_name = 3,
  field_operator = 4,
  field_params = 5,
  field_term = 6,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_body] = "body",
  [field_initial] = "initial",
  [field_name] = "name",
  [field_operator] = "operator",
  [field_params] = "params",
  [field_term] = "term",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 2},
  [2] = {.index = 2, .length = 2},
  [3] = {.index = 4, .length = 2},
  [4] = {.index = 6, .length = 2},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_body, 3},
    {field_name, 1},
  [2] =
    {field_initial, 3},
    {field_name, 1},
  [4] =
    {field_operator, 0},
    {field_term, 1},
  [6] =
    {field_body, 3},
    {field_params, 1},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 13,
  [15] = 15,
  [16] = 9,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 5,
  [25] = 23,
  [26] = 20,
  [27] = 27,
  [28] = 28,
  [29] = 28,
  [30] = 18,
  [31] = 17,
  [32] = 32,
  [33] = 32,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(12);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == ')') ADVANCE(19);
      if (lookahead == '-') ADVANCE(3);
      if (lookahead == ':') ADVANCE(14);
      if (lookahead == '=') ADVANCE(13);
      if (lookahead == '\\') ADVANCE(16);
      if (lookahead == '{') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 1:
      if (lookahead == '*') ADVANCE(6);
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 2:
      if (lookahead == '-') ADVANCE(21);
      END_STATE();
    case 3:
      if (lookahead == '-') ADVANCE(21);
      if (lookahead == '>') ADVANCE(17);
      END_STATE();
    case 4:
      if (lookahead == '-') ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '-') ADVANCE(9);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (lookahead == ':') ADVANCE(10);
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 7:
      if (lookahead == '>') ADVANCE(15);
      END_STATE();
    case 8:
      if (lookahead == 'n') ADVANCE(1);
      if (lookahead == 'p') ADVANCE(1);
      if (lookahead == '*' ||
          lookahead == 'a' ||
          lookahead == 'b' ||
          lookahead == 'd' ||
          lookahead == 'e' ||
          lookahead == '~') ADVANCE(6);
      END_STATE();
    case 9:
      if (lookahead == '}') ADVANCE(22);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 10:
      if (lookahead == 'h' ||
          lookahead == 's' ||
          lookahead == 'w') ADVANCE(7);
      END_STATE();
    case 11:
      if (eof) ADVANCE(12);
      if (lookahead == '(') ADVANCE(18);
      if (lookahead == '-') ADVANCE(2);
      if (lookahead == '=') ADVANCE(8);
      if (lookahead == '{') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(11);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(sym_step_operator);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_BSLASH);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_DASH_GT);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_LPAREN);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(anon_sym_RPAREN);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == '#' ||
          lookahead == '\'' ||
          ('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(20);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(sym_line_comment);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(21);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (lookahead == 'c') ADVANCE(1);
      if (lookahead == 'e') ADVANCE(2);
      if (lookahead == 'l') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'o') ADVANCE(4);
      END_STATE();
    case 2:
      if (lookahead == 'v') ADVANCE(5);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(6);
      END_STATE();
    case 4:
      if (lookahead == 'n') ADVANCE(7);
      END_STATE();
    case 5:
      if (lookahead == 'a') ADVANCE(8);
      END_STATE();
    case 6:
      if (lookahead == 't') ADVANCE(9);
      END_STATE();
    case 7:
      if (lookahead == 'f') ADVANCE(10);
      END_STATE();
    case 8:
      if (lookahead == 'l') ADVANCE(11);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(anon_sym_let);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(anon_sym_conf);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_eval);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0},
  [1] = {.lex_state = 0},
  [2] = {.lex_state = 11},
  [3] = {.lex_state = 11},
  [4] = {.lex_state = 11},
  [5] = {.lex_state = 11},
  [6] = {.lex_state = 0},
  [7] = {.lex_state = 0},
  [8] = {.lex_state = 0},
  [9] = {.lex_state = 0},
  [10] = {.lex_state = 0},
  [11] = {.lex_state = 0},
  [12] = {.lex_state = 0},
  [13] = {.lex_state = 0},
  [14] = {.lex_state = 0},
  [15] = {.lex_state = 0},
  [16] = {.lex_state = 0},
  [17] = {.lex_state = 11},
  [18] = {.lex_state = 11},
  [19] = {.lex_state = 11},
  [20] = {.lex_state = 11},
  [21] = {.lex_state = 11},
  [22] = {.lex_state = 11},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 0},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 0},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 0},
  [37] = {.lex_state = 0},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 0},
  [40] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [anon_sym_let] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_eval] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_conf] = ACTIONS(1),
    [anon_sym_BSLASH] = ACTIONS(1),
    [anon_sym_DASH_GT] = ACTIONS(1),
    [anon_sym_LPAREN] = ACTIONS(1),
    [anon_sym_RPAREN] = ACTIONS(1),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(35),
    [sym__statement] = STATE(12),
    [sym_let_binding] = STATE(12),
    [sym_eval_block] = STATE(12),
    [sym_conf_block] = STATE(12),
    [aux_sym_source_file_repeat1] = STATE(12),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_let] = ACTIONS(7),
    [anon_sym_eval] = ACTIONS(9),
    [anon_sym_conf] = ACTIONS(11),
    [sym_line_comment] = ACTIONS(3),
    [sym_block_comment] = ACTIONS(3),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 8,
    ACTIONS(13), 1,
      ts_builtin_sym_end,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_step_operator,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(21), 2,
      sym_reduction_step,
      aux_sym_eval_block_repeat1,
    ACTIONS(17), 3,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
    STATE(18), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [31] = 8,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(19), 1,
      sym_step_operator,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(23), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(19), 2,
      sym_reduction_step,
      aux_sym_eval_block_repeat1,
    ACTIONS(25), 3,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
    STATE(18), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [62] = 6,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(27), 2,
      ts_builtin_sym_end,
      sym_step_operator,
    ACTIONS(29), 3,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
    STATE(18), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [87] = 6,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(31), 2,
      ts_builtin_sym_end,
      sym_step_operator,
    ACTIONS(33), 3,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
    STATE(18), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [112] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(11), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [134] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(3), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [156] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(2), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [178] = 5,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(23), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [200] = 6,
    ACTIONS(45), 1,
      ts_builtin_sym_end,
    ACTIONS(47), 1,
      anon_sym_let,
    ACTIONS(50), 1,
      anon_sym_eval,
    ACTIONS(53), 1,
      anon_sym_conf,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 5,
      sym__statement,
      sym_let_binding,
      sym_eval_block,
      sym_conf_block,
      aux_sym_source_file_repeat1,
  [224] = 6,
    ACTIONS(15), 1,
      sym_identifier,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(56), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(58), 3,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
    STATE(18), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [248] = 6,
    ACTIONS(7), 1,
      anon_sym_let,
    ACTIONS(9), 1,
      anon_sym_eval,
    ACTIONS(11), 1,
      anon_sym_conf,
    ACTIONS(60), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(10), 5,
      sym__statement,
      sym_let_binding,
      sym_eval_block,
      sym_conf_block,
      aux_sym_source_file_repeat1,
  [272] = 5,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(24), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [294] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(5), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [316] = 5,
    ACTIONS(21), 1,
      anon_sym_LPAREN,
    ACTIONS(35), 1,
      sym_identifier,
    ACTIONS(37), 1,
      anon_sym_BSLASH,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(4), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [338] = 5,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(41), 1,
      anon_sym_BSLASH,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(25), 6,
      sym__term,
      sym_lambda,
      sym_application,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [360] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 3,
      ts_builtin_sym_end,
      sym_step_operator,
      anon_sym_LPAREN,
    ACTIONS(64), 4,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
      sym_identifier,
  [376] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(66), 3,
      ts_builtin_sym_end,
      sym_step_operator,
      anon_sym_LPAREN,
    ACTIONS(68), 4,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
      sym_identifier,
  [392] = 4,
    ACTIONS(19), 1,
      sym_step_operator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_reduction_step,
      aux_sym_eval_block_repeat1,
    ACTIONS(70), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
  [410] = 3,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(72), 3,
      ts_builtin_sym_end,
      sym_step_operator,
      anon_sym_LPAREN,
    ACTIONS(74), 4,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
      sym_identifier,
  [426] = 4,
    ACTIONS(19), 1,
      sym_step_operator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_reduction_step,
      aux_sym_eval_block_repeat1,
    ACTIONS(76), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
  [444] = 4,
    ACTIONS(80), 1,
      sym_step_operator,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(22), 2,
      sym_reduction_step,
      aux_sym_eval_block_repeat1,
    ACTIONS(78), 4,
      ts_builtin_sym_end,
      anon_sym_let,
      anon_sym_eval,
      anon_sym_conf,
  [462] = 5,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(83), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(30), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [481] = 5,
    ACTIONS(31), 1,
      anon_sym_RPAREN,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(30), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [500] = 5,
    ACTIONS(39), 1,
      sym_identifier,
    ACTIONS(43), 1,
      anon_sym_LPAREN,
    ACTIONS(85), 1,
      anon_sym_RPAREN,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    STATE(30), 3,
      sym__atom,
      sym_variable,
      sym_paren_term,
  [519] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(72), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
  [529] = 4,
    ACTIONS(87), 1,
      sym_identifier,
    ACTIONS(90), 1,
      anon_sym_DASH_GT,
    STATE(27), 1,
      aux_sym_lambda_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [543] = 4,
    ACTIONS(92), 1,
      sym_identifier,
    ACTIONS(94), 1,
      anon_sym_DASH_GT,
    STATE(27), 1,
      aux_sym_lambda_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [557] = 4,
    ACTIONS(92), 1,
      sym_identifier,
    ACTIONS(96), 1,
      anon_sym_DASH_GT,
    STATE(27), 1,
      aux_sym_lambda_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [571] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(66), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
  [581] = 2,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
    ACTIONS(62), 3,
      anon_sym_LPAREN,
      anon_sym_RPAREN,
      sym_identifier,
  [591] = 3,
    ACTIONS(98), 1,
      sym_identifier,
    STATE(29), 1,
      aux_sym_lambda_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [602] = 3,
    ACTIONS(100), 1,
      sym_identifier,
    STATE(28), 1,
      aux_sym_lambda_repeat1,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [613] = 2,
    ACTIONS(102), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [621] = 2,
    ACTIONS(104), 1,
      ts_builtin_sym_end,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [629] = 2,
    ACTIONS(106), 1,
      anon_sym_EQ,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [637] = 2,
    ACTIONS(108), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [645] = 2,
    ACTIONS(110), 1,
      sym_identifier,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [653] = 2,
    ACTIONS(112), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
  [661] = 2,
    ACTIONS(114), 1,
      anon_sym_COLON,
    ACTIONS(3), 2,
      sym_line_comment,
      sym_block_comment,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 31,
  [SMALL_STATE(4)] = 62,
  [SMALL_STATE(5)] = 87,
  [SMALL_STATE(6)] = 112,
  [SMALL_STATE(7)] = 134,
  [SMALL_STATE(8)] = 156,
  [SMALL_STATE(9)] = 178,
  [SMALL_STATE(10)] = 200,
  [SMALL_STATE(11)] = 224,
  [SMALL_STATE(12)] = 248,
  [SMALL_STATE(13)] = 272,
  [SMALL_STATE(14)] = 294,
  [SMALL_STATE(15)] = 316,
  [SMALL_STATE(16)] = 338,
  [SMALL_STATE(17)] = 360,
  [SMALL_STATE(18)] = 376,
  [SMALL_STATE(19)] = 392,
  [SMALL_STATE(20)] = 410,
  [SMALL_STATE(21)] = 426,
  [SMALL_STATE(22)] = 444,
  [SMALL_STATE(23)] = 462,
  [SMALL_STATE(24)] = 481,
  [SMALL_STATE(25)] = 500,
  [SMALL_STATE(26)] = 519,
  [SMALL_STATE(27)] = 529,
  [SMALL_STATE(28)] = 543,
  [SMALL_STATE(29)] = 557,
  [SMALL_STATE(30)] = 571,
  [SMALL_STATE(31)] = 581,
  [SMALL_STATE(32)] = 591,
  [SMALL_STATE(33)] = 602,
  [SMALL_STATE(34)] = 613,
  [SMALL_STATE(35)] = 621,
  [SMALL_STATE(36)] = 629,
  [SMALL_STATE(37)] = 637,
  [SMALL_STATE(38)] = 645,
  [SMALL_STATE(39)] = 653,
  [SMALL_STATE(40)] = 661,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(37),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [13] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conf_block, 4, 0, 2),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(17),
  [17] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_conf_block, 4, 0, 2),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [23] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_block, 4, 0, 2),
  [25] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_eval_block, 4, 0, 2),
  [27] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_reduction_step, 2, 0, 3),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_reduction_step, 2, 0, 3),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_lambda, 4, 0, 4),
  [33] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_lambda, 4, 0, 4),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(17),
  [37] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [39] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [41] = {.entry = {.count = 1, .reusable = true}}, SHIFT(33),
  [43] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [45] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [47] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [50] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [53] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(34),
  [56] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_let_binding, 4, 0, 1),
  [58] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_let_binding, 4, 0, 1),
  [60] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [62] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_variable, 1, 0, 0),
  [64] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_variable, 1, 0, 0),
  [66] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_application, 2, 0, 0),
  [68] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_application, 2, 0, 0),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_eval_block, 5, 0, 2),
  [72] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paren_term, 3, 0, 0),
  [74] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paren_term, 3, 0, 0),
  [76] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_conf_block, 5, 0, 2),
  [78] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_eval_block_repeat1, 2, 0, 0),
  [80] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_eval_block_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [83] = {.entry = {.count = 1, .reusable = true}}, SHIFT(20),
  [85] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_lambda_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [90] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_lambda_repeat1, 2, 0, 0),
  [92] = {.entry = {.count = 1, .reusable = true}}, SHIFT(27),
  [94] = {.entry = {.count = 1, .reusable = true}}, SHIFT(13),
  [96] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [98] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [100] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [102] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [104] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
};

#ifdef __cplusplus
extern "C" {
#endif
#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_elsa(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
